NORMALIZED_NAMES = {
    "Urnula craterium": "урнула",
    "Leccinum albostipitatum": "подосиновик",
    "Lactarius deliciosus": "рыжик",
    "Clitocybe nebularis": "говорушка",
    "Hypholoma fasciculare": "ложный опёнок",
    "Lactarius torminosus": "волнушка",
    "Lycoperdon perlatum": "дождевик",
    "Verpa bohemica": "сморчковая шапочка",
    "Schizophyllum commune": "щелелистник",
    "Leccinum aurantiacum": "подосиновик",
    "Phellinus igniarius": "трутовик",
    "Suillus luteus": "маслёнок",
    "Coltricia perennis": "трутовик",
    "Cetraria islandica": "лишайник",
    "Amanita muscaria": "мухомор",
    "Pholiota aurivella": "чешуйчатка",
    "Trichaptum biforme": "трутовик",
    "Artomyces pyxidatus": "рогатик",
    "Calocera viscosa": "калоцера",
    "Sarcosoma globosum": "саркосома",
    "Evernia prunastri": "лишайник",
    "Laetiporus sulphureus": "трутовик",
    "Lobaria pulmonaria": "лишайник",
    "Bjerkandera adusta": "трутовик",
    "Vulpicida pinastri": "лишайник",
    "Imleria badia": "польский гриб",
    "Evernia mesomorpha": "лишайник",
    "Physcia adscendens": "лишайник",
    "Coprinellus micaceus": "навозник",
    "Armillaria borealis": "опёнок",
    "Trametes ochracea": "трутовик",
    "Cantharellus cibarius": "лисичка",
    "Pseudevernia furfuracea": "лишайник",
    "Tremella mesenterica": "дрожалка",
    "Gyromitra infula": "строчок",
    "Leccinum versipelle": "подосиновик",
    "Mutinus ravenelii": "мутинус",
    "Pholiota squarrosa": "чешуйчатка",
    "Amanita rubescens": "мухомор",
    "Amanita pantherina": "мухомор",
    "Sarcoscypha austriaca": "саркосцифа",
    "Boletus edulis": "белый гриб",
    "Coprinus comatus": "навозник",
    "Merulius tremellosus": "трутовик",
    "Stropharia aeruginosa": "строфария",
    "Cladonia fimbriata": "лишайник",
    "Suillus grevillei": "маслёнок",
    "Apioperdon pyriforme": "дождевик",
    "Cerioporus squamosus": "трутовик",
    "Leccinum scabrum": "подберёзовик",
    "Rhytisma acerinum": "ризтисма",
    "Hypholoma lateritium": "ложный опёнок",
    "Flammulina velutipes": "опёнок",
    "Tricholomopsis rutilans": "рядовка",
    "Coprinopsis atramentaria": "навозник",
    "Trametes versicolor": "трутовик",
    "Graphis scripta": "лишайник",
    "Ganoderma applanatum": "трутовик",
    "Phellinus tremulae": "трутовик",
    "Peltigera aphthosa": "лишайник",
    "Parmelia sulcata": "лишайник",
    "Fomitopsis betulina": "трутовик",
    "Pleurotus pulmonarius": "вёшенка",
    "Fomitopsis pinicola": "трутовик",
    "Daedaleopsis confragosa": "трутовик",
    "Hericium coralloides": "ежовик",
    "Trametes hirsuta": "трутовик",
    "Coprinellus disseminatus": "навозник",
    "Kuehneromyces mutabilis": "опёнок",
    "Pleurotus ostreatus": "вёшенка",
    "Phlebia radiata": "трутовик",
    "Boletus reticulatus": "белый гриб",
    "Phallus impudicus": "весёлка",
    "Macrolepiota procera": "зонтик",
    "Fomes fomentarius": "трутовик",
    "Suillus granulatus": "маслёнок",
    "Gyromitra esculenta": "строчок",
    "Xanthoria parietina": "лишайник",
    "Nectria cinnabarina": "нектрия",
    "Sarcomyxa serotina": "вёшенка",
    "Inonotus obliquus": "чага",
    "Panellus stipticus": "панеллюс",
    "Hypogymnia physodes": "лишайник",
    "Hygrophoropsis aurantiaca": "ложная лисичка",
    "Cladonia rangiferina": "лишайник",
    "Platismatia glauca": "лишайник",
    "Calycina citrina": "биспорелла",
    "Cladonia stellaris": "лишайник",
    "Amanita citrina": "мухомор",
    "Lepista nuda": "рядовка",
    "Gyromitra gigas": "строчок",
    "Crucibulum laeve": "круцибулюм",
    "Daedaleopsis tricolor": "трутовик",
    "Stereum hirsutum": "стереум",
    "Paxillus involutus": "свинушка",
    "Lactarius turpis": "груздь",
    "Chlorociboria aeruginascens": "хлороцибория",
    "Chondrostereum purpureum": "хондростереум",
    "Phaeophyscia orbicularis": "лишайник",
    "Peltigera praetextata": "лишайник"
}


MUSHROOM_STATUS = {

    "Amanita muscaria": "Ядовитый",
    "Amanita pantherina": "Смертельно ядовитый",
    "Amanita citrina": "Несъедобный (слабо ядовитый)",
    "Hypholoma fasciculare": "Ядовитый (ложноопёнок)",
    "Paxillus involutus": "Ядовитый (коварный гриб)",
    "Gyromitra esculenta": "Условно съедобный (требует спец. обработки)",
    "Gyromitra infula": "Ядовитый/Несъедобный",
    
    "Boletus edulis": "Съедобный (Белый гриб)",
    "Boletus reticulatus": "Съедобный (Сетчатый белый)",
    "Cantharellus cibarius": "Съедобный (Лисичка обыкновенная)",
    "Lactarius deliciosus": "Съедобный (Рыжик)",
    "Leccinum aurantiacum": "Съедобный (Подосиновик)",
    "Leccinum scabrum": "Съедобный (Подберёзовик)",
    "Suillus luteus": "Съедобный (Маслёнок)",
    "Imleria badia": "Съедобный (Польский гриб)",
    "Armillaria borealis": "Съедобный (Опёнок северный)",
    "Flammulina velutipes": "Съедобный (Зимний опёнок)",
    "Pleurotus ostreatus": "Съедобный (Вёшенка)",
}

def get_mushroom_info(original_name: str) -> dict:
    return {
        "name_ru": NORMALIZED_NAMES.get(original_name, original_name),
        "status": MUSHROOM_STATUS.get(original_name, "Неизвестно ( будьте осторожны )"),
    }

def normalize_mushroom_name(original_name: str) -> str:
    return NORMALIZED_NAMES.get(original_name, original_name)